version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/API_AGENT_CODE

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  # [删除] 既然 install.sh 里已经强制写入了，就不需要 BeforeInstall 备份了1111
  # BeforeInstall:
  #   - location: scripts/backup_config.sh
  #     timeout: 60
  #     runas: root

  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root