version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/API_AGENT_CODE

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  # [新增] 在文件复制之前，先备份现有的配置文件
  # 注意：你需要确保 scripts/backup_config.sh 文件已存在于你的仓库中
  BeforeInstall:
    - location: scripts/backup_config.sh
      timeout: 60
      runas: root

  AfterInstall:
    # [已删除] scripts/sync_repo.sh (防止它从 git 拉取旧配置覆盖服务器)
    
    # 只运行安装脚本
    - location: scripts/install.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root