version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/API_AGENT_CODE

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/sync_repo.sh
      timeout: 300
      runas: ubuntu
    - location: scripts/install.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root
